version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres-userservice
    restart: always
    environment:
      POSTGRES_DB: userservice
      POSTGRES_USER: dbowner
      POSTGRES_PASSWORD: dbowner
      TZ: Asia/Ho_Chi_Minh
      PGTZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "timezone=Asia/Ho_Chi_Minh"]
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
volumes:
  postgres_data:
  redis_data: