version: "3.9"

services:
  postgres-userservice:
    image: postgres
    container_name: postgres-userservice
    restart: always
    environment:
      POSTGRES_DB: userservice
      POSTGRES_USER: dbowner
      POSTGRES_PASSWORD: dbowner
      TZ: Asia/Ho_Chi_Minh
      PGTZ: Asia/Ho_Chi_Minh
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "timezone=Asia/Ho_Chi_Minh"]
  postgres-contentservice:
    image: postgres
    container_name: postgres-contentservice
    restart: always
    environment:
      POSTGRES_DB: contentservice
      POSTGRES_USER: dbowner
      POSTGRES_PASSWORD: dbowner
      TZ: Asia/Ho_Chi_Minh
      PGTZ: Asia/Ho_Chi_Minh
    ports:
      - "5433:5432"
    volumes:
      - postgres_content_data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "timezone=Asia/Ho_Chi_Minh" ]
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC
    volumes:
      - ./qdrant_storage:/qdrant/storage  # map volume để lưu dữ liệu
volumes:
  postgres_user_data:
  postgres_content_data:
  redis_data: