server:
    port: 8080
app:
    api-prefix: /api
    user-service: ${USER_SERVICE_URL:http://localhost:8081/user-service/}
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
            -   id: user-service
                uri: ${USER_SERVICE_URL:http://localhost:8081}
                predicates:
                - Path=${app.api-prefix}/user-service/**
                filters:
                - StripPrefix=1
            -   id: content-service
                uri: ${CONTENT_SERVICE_URL:http://localhost:8082}
                predicates:
                    - Path=${app.api-prefix}/content-service/**
                filters:
                    - StripPrefix=1
            -   id: learning-service
                uri: ${LEARNING_SERVICE_URL:http://loccalhost:8083}
                predicates:
                  - Path=${app.api-prefix}/learning-service/**
            -   id: agent-service
                uri: ${AGENT_SERVICE_URL:http://localhost:5000}
                predicates:
                    - Path=${app.api-prefix}/agent-service/**
                filters:
                    - StripPrefix=1
