server:
    port: 8080
app:
    api-prefix: /api
    user-service: ${USER_SERVICE:http://localhost:8081/user-service/}
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
            -   id: user-service
                uri: http://localhost:8081
                predicates:
                - Path=${app.api-prefix}/user-service/**
                filters:
                - StripPrefix=1
            - id: content-service
              uri: http://localhost:8082
              predicates:
                  - Path=${app.api-prefix}/content-service/**
              filters:
                  - StripPrefix=1
