spring:
  application:
    name: content-service
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://localhost:5433/contentservice
    username: dbowner
    password: dbowner

server:
  port: 8082
  servlet:
    context-path: /content-service

cloudinary:
  cloud_name: ${CLOUD_NAME:dwhlihfnn}
  api_key: ${API_KEY:649188967252551}
  api_secret: ${API_SECRET:1wSx5Uul_Be3jt9QAG1xG_kexYA}